# Generated by Django 4.2.6 on 2023-11-14 17:26

import ccam.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coordinators", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=40, verbose_name="Nome do curso")),
                (
                    "duration",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(8)],
                        verbose_name="Duração (em anos/períodos)",
                    ),
                ),
                (
                    "coordinator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator",
                        to="coordinators.coordinator",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=40, verbose_name="Disciplina")),
                ("course", models.ManyToManyField(related_name="subject_courses", to="academics.course")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
    ]
