# Generated by Django 4.2.6 on 2023-11-14 17:32

import ccam.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("seac", "0004_alter_seacstaff_phone_line_alter_seacstaff_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_certificate_assessor",
                        to="seac.seacstaff",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_certificate_student",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Certificate",
                "verbose_name_plural": "Knowledge Certificates",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeCGrades",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)], verbose_name="Nota"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_knowledge_certificate",
                        to="academics.knowledgecertificate",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_certificate_subject",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KnowledgeCGrades",
                "verbose_name_plural": "KnowledgeCGrades",
            },
        ),
        migrations.AddField(
            model_name="knowledgecertificate",
            name="subjects",
            field=models.ManyToManyField(
                related_name="knowledge_certifiace_subjects",
                through="academics.KnowledgeCGrades",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="knowledgecertificate",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=models.SET(ccam.core.models.get_sentinel_user),
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
