# Generated by Django 4.2.6 on 2023-11-14 17:33

import ccam.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("seac", "0004_alter_seacstaff_phone_line_alter_seacstaff_role"),
        ("students", "0001_initial"),
        ("academics", "0002_knowledgecertificate_knowledgecgrades_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectDGrades",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                (
                    "compatibility",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)], verbose_name="Compatibilidade"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_dispensal_subject",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubjectDGrades",
                "verbose_name_plural": "SubjectDGrades",
            },
        ),
        migrations.CreateModel(
            name="SubjectDispensal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_dispensal_assessor",
                        to="seac.seacstaff",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_dispensal_student",
                        to="students.student",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="subject_dispensal_subjects",
                        through="academics.SubjectDGrades",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Dispensal",
                "verbose_name_plural": "Subject Dispensals",
            },
        ),
        migrations.AddField(
            model_name="subjectdgrades",
            name="subject_dispensal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specific_subject_dispensal",
                to="academics.subjectdispensal",
            ),
        ),
        migrations.AddField(
            model_name="subjectdgrades",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=models.SET(ccam.core.models.get_sentinel_user),
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
