# Generated by Django 4.2.6 on 2023-11-14 19:14

import ccam.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0001_initial"),
        ("coordinators", "0001_initial"),
        ("academics", "0003_subjectdgrades_subjectdispensal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="grade_semester_availability",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(8)], verbose_name="Ano/Período"
            ),
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_coordinator",
                        to="coordinators.coordinator",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_subject",
                        to="academics.subject",
                    ),
                ),
                ("teachers", models.ManyToManyField(related_name="committee_teachers", to="teachers.teacher")),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee",
                "verbose_name_plural": "Committees",
            },
        ),
    ]
