# Generated by Django 4.2.6 on 2023-11-14 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_subject_grade_semester_availability_committee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="knowledgecertificate",
            old_name="accessed_by",
            new_name="assessed_by",
        ),
        migrations.RenameField(
            model_name="subjectdispensal",
            old_name="accessed_by",
            new_name="assessed_by",
        ),
    ]
