# Generated by Django 4.2.6 on 2023-11-14 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_rename_accessed_by_knowledgecertificate_assessed_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committee",
            options={"verbose_name": "Banca", "verbose_name_plural": "Bancas"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
        migrations.AlterModelOptions(
            name="knowledgecertificate",
            options={
                "verbose_name": "Certificação de Conhecimento",
                "verbose_name_plural": "Certificação de Conhecimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgecgrades",
            options={"verbose_name": "CertificaçãoCNotas", "verbose_name_plural": "CertificaçãoCNotas"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Disciplina", "verbose_name_plural": "Disciplinas"},
        ),
        migrations.AlterModelOptions(
            name="subjectdgrades",
            options={
                "verbose_name": "AproveitamentoDCompatibilidades",
                "verbose_name_plural": "AproveitamentoDCompatibilidades",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectdispensal",
            options={
                "verbose_name": "Aproveitamento de Disciplina",
                "verbose_name_plural": "Aproveitamento de Disciplinas",
            },
        ),
    ]
