# Generated by Django 4.2.6 on 2023-11-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coordinators", "0002_alter_coordinator_options"),
        ("academics", "0006_alter_committee_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coordinator",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinator",
                to="coordinators.coordinator",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=280, verbose_name="Nome do curso"),
        ),
    ]
