# Generated by Django 4.2.6 on 2023-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_alter_teacher_options"),
        ("academics", "0007_alter_course_coordinator_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(to="teachers.teacher"),
        ),
    ]
