# Generated by Django 4.2.6 on 2023-11-18 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_subject_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teachers",
        ),
    ]
