# Generated by Django 4.2.6 on 2023-11-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coordinators", "0002_alter_coordinator_options"),
        ("academics", "0009_remove_subject_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coordinator",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="coordinators.coordinator",
            ),
        ),
    ]
