# Generated by Django 4.2.6 on 2023-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0010_alter_course_coordinator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="course",
            field=models.ManyToManyField(related_name="subjects", to="academics.course"),
        ),
    ]
