# Generated by Django 4.2.6 on 2023-11-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_alter_subject_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="educational_level",
            field=models.CharField(
                choices=[("TEEM", "Técnico Médio Integrado"), ("UNI", "Superior")],
                default="UNI",
                max_length=4,
                verbose_name="Nível Educacional",
            ),
            preserve_default=False,
        ),
    ]
