# Generated by Django 4.2.6 on 2023-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0012_subject_educational_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="course",
            field=models.ManyToManyField(related_name="subjects", to="academics.course", verbose_name="Cursos"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Nome da Disciplina"),
        ),
    ]
