# Generated by Django 4.2.6 on 2023-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0012_subject_educational_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="course",
            field=models.ManyToManyField(related_name="subjects", to="academics.course", verbose_name="Cursos"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade_semester_availability",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "First"),
                    (2, "Second"),
                    (3, "Third"),
                    (4, "Fourth"),
                    (5, "Fifth"),
                    (6, "Sixth"),
                    (7, "Seventh"),
                    (8, "Eighth"),
                ],
                verbose_name="Ano/Período",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Nome da Disciplina"),
        ),
    ]
