# Generated by Django 4.2.6 on 2023-11-28 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0013_alter_subject_course_alter_subject_name"),
        ("academics", "0013_alter_subject_course_and_more"),
    ]

    operations = []
