# Generated by Django 4.2.6 on 2023-12-05 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0014_merge_20231128_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgecertificate",
            name="submission_date",
            field=models.DateField(default=datetime.date(2023, 12, 4), verbose_name="Data de Submissão"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade_semester_availability",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1º"), (2, "2º"), (3, "3º"), (4, "4º"), (5, "5º"), (6, "6º"), (7, "7º"), (8, "8º")],
                verbose_name="Ano/Período",
            ),
        ),
    ]
