# Generated by Django 4.2.6 on 2023-12-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("seac", "0005_alter_seacstaff_options"),
        ("academics", "0014_merge_20231128_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgecertificate",
            name="status",
            field=models.CharField(
                choices=[("AP", "Aprovado"), ("PR", "Em análise"), ("ERR", "Recusado")],
                default="PR",
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgecertificate",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_certificate_assessor",
                to="seac.seacstaff",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade_semester_availability",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1º"), (2, "2º"), (3, "3º"), (4, "4º"), (5, "5º"), (6, "6º"), (7, "7º"), (8, "8º")],
                verbose_name="Ano/Período",
            ),
        ),
    ]
