# Generated by Django 4.2.6 on 2023-12-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("seac", "0005_alter_seacstaff_options"),
        ("students", "0003_alter_student_current_grade_semester"),
        ("academics", "0015_knowledgecertificate_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgecertificate",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessor",
                to="seac.seacstaff",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgecertificate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="student", to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgecertificate",
            name="subjects",
            field=models.ManyToManyField(
                related_name="knowledge_certificates", through="academics.KnowledgeCGrades", to="academics.subject"
            ),
        ),
    ]
