# Generated by Django 4.2.6 on 2023-12-05 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0015_knowledgecertificate_submission_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectdispensal",
            name="submission_date",
            field=models.DateField(default=datetime.date(2023, 12, 4), verbose_name="Data de Submissão"),
        ),
    ]
