# Generated by Django 4.2.6 on 2023-12-05 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0016_subjectdispensal_submission_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgecertificate",
            name="submission_date",
        ),
        migrations.RemoveField(
            model_name="subjectdispensal",
            name="submission_date",
        ),
    ]
