# Generated by Django 4.2.6 on 2023-12-01 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0017_alter_knowledgecgrades_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgecgrades",
            name="grade",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name="Nota"
            ),
        ),
    ]
