# Generated by Django 4.2.6 on 2023-12-02 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0018_alter_knowledgecgrades_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgecgrades",
            name="changed_at",
        ),
        migrations.RemoveField(
            model_name="knowledgecgrades",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="knowledgecgrades",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="knowledgecgrades",
            name="updated_by",
        ),
    ]
