# Generated by Django 4.2.6 on 2023-12-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_student_current_grade_semester"),
        ("academics", "0019_remove_knowledgecgrades_changed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgecertificate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_knowledge_certificates",
                to="students.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgecertificate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PR")),
                fields=("student", "status"),
                name="one-pending-request-per-student",
            ),
        ),
    ]
