# Generated by Django 4.2.6 on 2023-12-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0020_alter_knowledgecertificate_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgecertificate",
            name="justification",
            field=models.TextField(blank=True),
        ),
    ]
