# Generated by Django 4.2.6 on 2023-12-05 01:46

import ccam.academics.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0022_subjectdispensal_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectdispensal",
            name="previous_university_grades",
            field=models.FileField(default="", upload_to=ccam.academics.utils.get_subject_dispensal_files_dir),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectdispensal",
            name="previous_university_ppc",
            field=models.FileField(default="", upload_to=ccam.academics.utils.get_subject_dispensal_files_dir),
            preserve_default=False,
        ),
    ]
