# Generated by Django 4.2.6 on 2023-12-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0026_alter_subjectdgrades_compatibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectdgrades",
            name="changed_at",
        ),
        migrations.RemoveField(
            model_name="subjectdgrades",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="subjectdgrades",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="subjectdgrades",
            name="updated_by",
        ),
    ]
