# Generated by Django 4.2.6 on 2023-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0027_remove_subjectdgrades_changed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectdispensal",
            name="status",
            field=models.CharField(
                choices=[("AP", "Aprovado"), ("PR", "Em análise"), ("ERR", "Recusado")],
                default="PR",
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectdispensal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PR")),
                fields=("student", "status"),
                name="one-pending-subject-dispensal-request-per-student",
            ),
        ),
    ]
