# Generated by Django 4.2.6 on 2023-12-06 12:35

import ccam.academics.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_alter_teacher_subjects"),
        ("academics", "0028_subjectdispensal_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="teachers",
            field=models.ManyToManyField(blank=True, related_name="committee_teachers", to="teachers.teacher"),
        ),
        migrations.AlterField(
            model_name="subjectdispensal",
            name="previous_university_grades",
            field=models.FileField(
                upload_to=ccam.academics.utils.get_subject_dispensal_files_dir,
                verbose_name="Histórico da Antiga Universidade",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdispensal",
            name="previous_university_ppc",
            field=models.FileField(
                upload_to=ccam.academics.utils.get_subject_dispensal_files_dir,
                verbose_name="PPC da Antiga Universidade",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdispensal",
            name="subjects",
            field=models.ManyToManyField(
                related_name="subject_dispensal_subjects",
                through="academics.SubjectDGrades",
                to="academics.subject",
                verbose_name="Disciplinas",
            ),
        ),
    ]
