# Generated by Django 4.2.6 on 2023-12-07 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0017_remove_knowledgecertificate_submission_date_and_more"),
        ("academics", "0028_subjectdispensal_status_and_more"),
    ]

    operations = []
