# Generated by Django 4.2.6 on 2023-12-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0029_alter_committee_teachers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committee_subject",
                to="academics.subject",
                verbose_name="Disciplina",
            ),
        ),
    ]
