# Generated by Django 4.2.6 on 2023-12-07 11:59

import ccam.academics.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0029_merge_20231207_0859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectdispensal",
            name="previous_university_grades",
            field=models.FileField(
                upload_to=ccam.academics.utils.get_subject_dispensal_files_dir,
                verbose_name="Histórico da Antiga Universidade",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdispensal",
            name="previous_university_ppc",
            field=models.FileField(
                upload_to=ccam.academics.utils.get_subject_dispensal_files_dir,
                verbose_name="PPC da Antiga Universidade",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdispensal",
            name="subjects",
            field=models.ManyToManyField(
                related_name="subject_dispensal_subjects",
                through="academics.SubjectDGrades",
                to="academics.subject",
                verbose_name="Disciplinas",
            ),
        ),
    ]
