# Generated by Django 4.2.6 on 2023-12-09 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0030_alter_committee_subject"),
        ("academics", "0030_alter_subjectdispensal_previous_university_grades_and_more"),
    ]

    operations = []
