# Generated by Django 4.2.6 on 2023-11-14 17:26

import ccam.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0004_alter_person_sex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("changed_at", models.DateField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_person",
                        to="people.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=models.SET(ccam.core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordinator",
                "verbose_name_plural": "Coordinators",
            },
        ),
    ]
