# Generated by Django 4.2.6 on 2023-11-14 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coordinators", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coordinator",
            options={"verbose_name": "Coordenador", "verbose_name_plural": "Coordenadores"},
        ),
    ]
