# Generated by Django 4.2.6 on 2023-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_grade_semester",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1º"), (2, "2º"), (3, "3º"), (4, "4º"), (5, "5º"), (6, "6º"), (7, "7º"), (8, "8º")],
                verbose_name="Ano/Período",
            ),
        ),
    ]
