# Generated by Django 4.2.6 on 2023-11-07 12:03

import ccam.core.utils
import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "profile_picture",
                    models.ImageField(upload_to=ccam.core.utils.user_directory_path, verbose_name="Foto de perfil"),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-mail")),
                ("registration", models.CharField(max_length=14, unique=True, verbose_name="Matrícula")),
                ("sex", models.CharField(choices=[("H", "Homem"), ("F", "Mulher")], max_length=1)),
                ("cpf", cpf_field.models.CPFField(max_length=14, unique=True, verbose_name="CPF")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="person", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
    ]
