# Generated by Django 4.2.6 on 2023-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_alter_person_created_by_alter_person_sex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(default="(84) 98185-0632", max_length=15, verbose_name="Fone"),
            preserve_default=False,
        ),
    ]
