# Generated by Django 4.2.6 on 2023-11-14 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_alter_person_sex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Pessoa", "verbose_name_plural": "Pessoas"},
        ),
    ]
