# Generated by Django 4.2.6 on 2023-11-22 18:10

import ccam.people.validators
import cpf_field.models
import cpf_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="cpf",
            field=cpf_field.models.CPFField(
                max_length=14,
                unique=True,
                validators=[ccam.people.validators.validate_cpf_mask, cpf_field.validators.validate_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(
                max_length=15, validators=[ccam.people.validators.phone_number_validator], verbose_name="Fone"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="registration",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[ccam.people.validators.registration_validator],
                verbose_name="Matrícula",
            ),
        ),
    ]
