# Generated by Django 4.2.6 on 2023-11-14 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Professor", "verbose_name_plural": "Professores"},
        ),
    ]
