# Generated by Django 4.2.6 on 2023-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_alter_subject_course"),
        ("teachers", "0002_alter_teacher_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                related_name="teacher_subjects", to="academics.subject", verbose_name="Matérias"
            ),
        ),
    ]
