MAX_LENGTH_NAME_FIELD = 80
MAX_LENGTH_REGISTRATION_FIELD = 14  # 20221094040009
MAX_LENGTH_PHONE_LINE_FIELD = 14  # (84) 4005 4109
TEACHER_GROUP_NAME = "Professor"
SEAC_COORDINATOR_GROUP_NAME = "Coordenador SEAC"
SEAC_EMPLOYEE_GROUP_NAME = "Funcionário da SEAC"
STUDENT_GROUP_NAME = "Estudante"
COURSE_COORDINATOR_GROUP_NAME = "Coordenador de Curso"
